USE DATABASE CS5542_DB;

CREATE OR REPLACE TABLE RAW.DOCS (
  DOC_ID STRING,
  TITLE STRING,
  SOURCE STRING,
  TEXT STRING,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE VIEW APP.V_APP_DATA AS
SELECT 
  DOC_ID,
  TITLE,
  SOURCE,
  LEFT(TEXT, 500) AS PREVIEW
FROM RAW.DOCS;
