-- Aggregation
SELECT SOURCE, COUNT(*) AS N_DOCS
FROM RAW.DOCS
GROUP BY SOURCE
ORDER BY N_DOCS DESC;

-- Time-based
SELECT DATE_TRUNC('DAY', CREATED_AT) AS DAY, COUNT(*) AS N
FROM RAW.DOCS
GROUP BY DAY
ORDER BY DAY DESC;

-- Filtered search
SELECT *
FROM APP.V_APP_DATA
WHERE PREVIEW ILIKE '%risk%'
LIMIT 20;
